env: dev
db_dsn: "host=zetian-personal-website-postgre.c1uyeekq4253.us-east-2.rds.amazonaws.com user=skylar27jin password=zetian-personal-website-postgre dbname=postgres port=5432 sslmode=require"
domain: "localhost" #store coookie to which domain
