// Code generated by hertz generator.

package main

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	numberOperation "zetian-personal-website-hertz/biz/model/numberOperation"
)

// GetToBinary .
// @router /to_binary [GET]
func GetToBinary(ctx context.Context, c *app.RequestContext) {
	var err error
	var req numberOperation.GetToBinaryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(numberOperation.GetToBinaryResp)

	c.JSON(consts.StatusOK, resp)
}
