// Code generated by hertz generator.

package numberOperation

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettobinaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _decodejwtMw() []app.HandlerFunc {
	// your code...
	return nil
}
