// Code generated by hertz generator.

package base

import (
	"context"

	category "zetian-personal-website-hertz/biz/model/category"
	"zetian-personal-website-hertz/biz/repository/category_repo"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetAllCategories .
// @router /category/all [GET]
func GetAllCategories(ctx context.Context, c *app.RequestContext) {

	var req category.GetAllCategoriesReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	categories, err := category_repo.GetAllCategoriesInCache()
	if err != nil {
		c.JSON(consts.StatusInternalServerError, category.GetAllCategoriesResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
		})
		return
	}

	thriftCategories := make([]*category.Category, 0, len(categories))
	for _, cat := range categories {
		thriftCategories = append(thriftCategories, &category.Category{
			ID:          cat.ID,
			Name:        cat.Name,
			Key:         cat.Key,
			Aliases:     cat.Aliases,
			Description: cat.Description,
		})
	}

	c.JSON(consts.StatusOK, category.GetAllCategoriesResp{
		IsSuccessful: true,
		ErrorMessage: "",
		Categories:   thriftCategories,
	})
}
