// Code generated by hertz generator.

package base

import (
	"context"
	"errors"
	"fmt"
	"time"

	"zetian-personal-website-hertz/biz/domain"
	post "zetian-personal-website-hertz/biz/model/post"
	"zetian-personal-website-hertz/biz/service/auth_service"
	"zetian-personal-website-hertz/biz/service/post_service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"gorm.io/gorm"
)

// GetPostByID .
// @router /post/get [GET]
func GetPostByID(ctx context.Context, c *app.RequestContext) {
	var req post.GetPostByIDReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if req.ID == 0 {
		c.JSON(consts.StatusBadRequest, post.GetPostByIDResp{
			IsSuccessful: false,
			ErrorMessage: "ID cannot be null",
			Post:         nil,
		})
		return
	}

	//get viewer from JWT
	viewerID := int64(-1)
	JWT := string(c.Cookie("JWT"))
	_, _, _, exp, id, err := auth_service.ParseUserJWT(ctx, JWT)
	if err == nil && exp > time.Now().Unix() {
		viewerID = id
	}
	// 若 JWT 不存在 / 解析失败 / 过期，则 viewerID 保持 -1，
	// 对应 service 中 IsLikedByUser / IsFavByUser 会默认 false。

	// 2) get post with like/fav counts and user flags
	domainPostFull, err := post_service.GetPostWithStats(ctx, req.ID, viewerID)
	if err != nil {
		c.JSON(consts.StatusBadRequest, post.GetPostByIDResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
			Post:         nil,
		})
		return
	}

	// 转 thrift.Post
	thriftPost := domain.FromDomainPostWithStatsToThriftPost(*domainPostFull)

	c.JSON(consts.StatusOK, post.GetPostByIDResp{
		IsSuccessful: true,
		ErrorMessage: "",
		Post:         &thriftPost,
	})
}

// CreatePost .
// @router /post/create [POST]
func CreatePost(ctx context.Context, c *app.RequestContext) {
	var err error
	var req post.CreatePostReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	JWT := string(c.Cookie("JWT"))
	_, _, _, exp, id, err := auth_service.ParseUserJWT(ctx, JWT)
	if err != nil || id != req.GetUserID() {
		c.JSON(consts.StatusUnauthorized, post.CreatePostResp{
			IsSuccessful: false,
			ErrorMessage: err.Error() + ": Please Create Post using your own account",
		})
		return
	}
	if exp < time.Now().Unix() {
		c.JSON(consts.StatusUnauthorized, post.CreatePostResp{
			IsSuccessful: false,
			ErrorMessage: "Authentification info expired, please login again",
		})
		return
	}

	domain_post_instance, err := post_service.CreatePost(ctx, req.GetUserID(), req.GetSchoolID(), req.GetTitle(), req.GetContent())
	if err != nil {
		c.JSON(consts.StatusInternalServerError, post.CreatePostResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
		})
		return
	}
	thriftPost := domain.FromDomainPostToThriftPost(*domain_post_instance)

	c.JSON(consts.StatusOK, post.CreatePostResp{
		IsSuccessful: true,
		ErrorMessage: "",
		Post:         &thriftPost,
	})

}

// EditPost .
// @router /post/edit [POST]
func EditPost(ctx context.Context, c *app.RequestContext) {
	var err error
	var req post.EditPostReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(post.EditPostResp)

	c.JSON(consts.StatusOK, resp)
}

// DeletePost .
// @router /post/delete [POST]
func DeletePost(ctx context.Context, c *app.RequestContext) {
	var err error
	var req post.DeletePostReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	fmt.Println("Entered DeletePost", req.GetID())
	JWT := string(c.Cookie("JWT"))
	_, _, _, exp, user_id, err := auth_service.ParseUserJWT(ctx, JWT)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, post.DeletePostResp{
			IsSuccessful: false,
			ErrorMessage: err.Error() + ": Please Delete Post using your own account",
		})
		return
	}
	if exp < time.Now().Unix() {
		c.JSON(consts.StatusUnauthorized, post.DeletePostResp{
			IsSuccessful: false,
			ErrorMessage: "Authentification info expired, please login again",
		})
		return
	}

	err = post_service.DeletePost(ctx, user_id, req.GetID())
	if errors.Is(err, gorm.ErrRecordNotFound) {
		c.JSON(consts.StatusNotFound, post.DeletePostResp{
			IsSuccessful: false,
			ErrorMessage: "Post not found or no permission.",
		})
		return
	}
	if err != nil {
		c.JSON(consts.StatusInternalServerError, post.DeletePostResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, post.DeletePostResp{
		IsSuccessful: true,
		ErrorMessage: "",
	})

}

// GetSchoolRecentPosts .
// @router /post/school/recent [GET]
func GetSchoolRecentPosts(ctx context.Context, c *app.RequestContext) {
	var err error
	var req post.GetSchoolRecentPostsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(post.GetSchoolRecentPostsResp)

	c.JSON(consts.StatusOK, resp)
}

// GetPersonalRecentPosts
// @router /post/personal [GET]
func GetPersonalRecentPosts(ctx context.Context, c *app.RequestContext) {
	var req post.GetPersonalRecentPostsReq

	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, post.GetPersonalRecentPostsResp{
			IsSuccessful: false,
			ErrorMessage: "Invalid request: " + err.Error(),
			Posts:        nil,
		})
		return
	}

	// get viewer from JWT
	viewerID := int64(-1)
	jwtStr := string(c.Cookie("JWT"))
	_, _, _, exp, id, err := auth_service.ParseUserJWT(ctx, jwtStr)
	if err == nil && exp > time.Now().Unix() {
		viewerID = id
	}

	postsWithStats, err := post_service.GetPersonalRecentPostsWithStats(
		ctx,
		req.UserID,
		viewerID,
		req.Before,
		int(req.Limit),
	)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, post.GetPersonalRecentPostsResp{
			IsSuccessful: false,
			ErrorMessage: "Failed to fetch posts: " + err.Error(),
			Posts:        nil,
		})
		return
	}

	// convert []domain.PostWithStats -> []thrift.Post
	thriftPosts := domain.FromPostWithStatsListToThriftPostList(postsWithStats)
	thriftPostPointers := make([]*post.Post, len(thriftPosts))
	for i := range thriftPosts {
		thriftPostPointers[i] = &thriftPosts[i]
	}

	resp := post.GetPersonalRecentPostsResp{
		IsSuccessful: true,
		ErrorMessage: "",
		Posts:        thriftPostPointers,
	}

	c.JSON(consts.StatusOK, resp)
}

// LikePost .
// @router /post/like [POST]
func LikePost(ctx context.Context, c *app.RequestContext) {
	var req post.LikePostReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, newFailedUserFlagPostResq("Invalid request: "+err.Error()))
		return
	}

	// 从 JWT 拿 userID（失败时内部会返回 401 并结束）
	userID, ok := getViewerIDFromJWTOrWriteUnauthorized(ctx, c)
	if !ok {
		return
	}

	// service 层：只信 JWT 的 userID，忽略 req.UserId
	if err := post_service.LikePost(ctx, userID, req.PostID); err != nil {
		c.JSON(consts.StatusOK, newFailedUserFlagPostResq(err.Error()))
		return
	}

	c.JSON(consts.StatusOK, newSuccessUserFlagPostResq())
}

// UnlikePost .
// @router /post/unlike [POST]
func UnlikePost(ctx context.Context, c *app.RequestContext) {
	var req post.UnlikePostReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, newFailedUserFlagPostResq("Invalid request: "+err.Error()))
		return
	}

	userID, ok := getViewerIDFromJWTOrWriteUnauthorized(ctx, c)
	if !ok {
		return
	}

	if err := post_service.UnlikePost(ctx, userID, req.PostID); err != nil {
		c.JSON(consts.StatusOK, newFailedUserFlagPostResq(err.Error()))
		return
	}

	c.JSON(consts.StatusOK, newSuccessUserFlagPostResq())
}

// FavPost .
// @router /post/fav [POST]
func FavPost(ctx context.Context, c *app.RequestContext) {
	var req post.FavPostReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, newFailedUserFlagPostResq("Invalid request: "+err.Error()))
		return
	}

	userID, ok := getViewerIDFromJWTOrWriteUnauthorized(ctx, c)
	if !ok {
		return
	}

	if err := post_service.FavoritePost(ctx, userID, req.PostID); err != nil {
		c.JSON(consts.StatusOK, newFailedUserFlagPostResq(err.Error()))
		return
	}

	c.JSON(consts.StatusOK, newSuccessUserFlagPostResq())
}

// UnfavPost .
// @router /post/unfav [POST]
func UnfavPost(ctx context.Context, c *app.RequestContext) {
	var req post.UnfavPostReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, newFailedUserFlagPostResq("Invalid request: "+err.Error()))
		return
	}

	userID, ok := getViewerIDFromJWTOrWriteUnauthorized(ctx, c)
	if !ok {
		return
	}

	if err := post_service.UnfavoritePost(ctx, userID, req.PostID); err != nil {
		c.JSON(consts.StatusOK, newFailedUserFlagPostResq(err.Error()))
		return
	}

	c.JSON(consts.StatusOK, newSuccessUserFlagPostResq())
}

// helper: build a failed UserFlagPostResq
func newFailedUserFlagPostResq(msg string) post.UserFlagPostResq {
	return post.UserFlagPostResq{
		IsSuccessful: false,
		ErrorMessage: msg,
	}
}

// helper: build a success UserFlagPostResq
func newSuccessUserFlagPostResq() post.UserFlagPostResq {
	return post.UserFlagPostResq{
		IsSuccessful: true,
		ErrorMessage: "",
	}
}

// helper: get viewerID from JWT cookie.
//
// 返回：
//   - viewerID: 合法用户 ID
//   - ok:       是否成功；如果 false，函数内部已经写了 Unauthorized 响应
func getViewerIDFromJWTOrWriteUnauthorized(
	ctx context.Context,
	c *app.RequestContext,
) (int64, bool) {
	jwtStr := string(c.Cookie("JWT"))

	_, _, _, exp, uid, errJWT := auth_service.ParseUserJWT(ctx, jwtStr)
	if errJWT != nil || exp <= time.Now().Unix() {
		// 解析失败或者过期
		c.JSON(consts.StatusUnauthorized, newFailedUserFlagPostResq("Unauthorized"))
		return -1, false
	}

	return uid, true
}
