// Code generated by hertz generator.

package base

import (
	"context"

	post "zetian-personal-website-hertz/biz/model/post"
	"zetian-personal-website-hertz/biz/service/post_service"
	"zetian-personal-website-hertz/biz/domain"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetPostByID .
// @router /post/get [GET]
func GetPostByID(ctx context.Context, c *app.RequestContext) {
	var err error
	var req post.GetPostByIDReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if req.ID == 0 {
		c.JSON(consts.StatusBadRequest, post.GetPostByIDResp{
			IsSuccessful: false,
			ErrorMessage: "ID cannot be null",
			Post: nil,
		})
		return 
	}

	domainPost, err := post_service.GetPostByID(ctx, req.ID)
	if err != nil {
		c.JSON(consts.StatusBadRequest, post.GetPostByIDResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
			Post: nil,
		})
		return
	}
	thriftPost := domain.FromDomainPostToThriftPost(*domainPost)


	c.JSON(consts.StatusOK, post.GetPostByIDResp{
			IsSuccessful: true,
			ErrorMessage: "",
			Post: &thriftPost,
	})
}

// CreatePost .
// @router /post/create [POST]
func CreatePost(ctx context.Context, c *app.RequestContext) {
	var err error
	var req post.CreatePostReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(post.CreatePostResp)

	c.JSON(consts.StatusOK, resp)
}

// EditPost .
// @router /post/edit [POST]
func EditPost(ctx context.Context, c *app.RequestContext) {
	var err error
	var req post.EditPostReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(post.EditPostResp)

	c.JSON(consts.StatusOK, resp)
}

// DeletePost .
// @router /post/delete [POST]
func DeletePost(ctx context.Context, c *app.RequestContext) {
	var err error
	var req post.DeletePostReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(post.DeletePostResp)

	c.JSON(consts.StatusOK, resp)
}

// GetSchoolRecentPosts .
// @router /post/school/recent [GET]
func GetSchoolRecentPosts(ctx context.Context, c *app.RequestContext) {
	var err error
	var req post.GetSchoolRecentPostsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(post.GetSchoolRecentPostsResp)

	c.JSON(consts.StatusOK, resp)
}

// GetAllPersonalPosts .
// @router /post/personal [GET]
func GetAllPersonalPosts(ctx context.Context, c *app.RequestContext) {
	var err error
	var req post.GetAllPersonalPostsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(post.GetAllPersonalPostsResp)

	c.JSON(consts.StatusOK, resp)
}
