// Code generated by hertz generator.

package base

import (
	"context"
	"errors"
	"fmt"
	"time"

	"zetian-personal-website-hertz/biz/domain"
	post "zetian-personal-website-hertz/biz/model/post"
	"zetian-personal-website-hertz/biz/service/auth_service"
	"zetian-personal-website-hertz/biz/service/picture_upload_service"
	"zetian-personal-website-hertz/biz/service/post_service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"gorm.io/gorm"
)

// GetPostByID .
// @router /post/get [GET]
func GetPostByID(ctx context.Context, c *app.RequestContext) {
	var req post.GetPostByIDReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if req.ID == 0 {
		c.JSON(consts.StatusBadRequest, post.GetPostByIDResp{
			IsSuccessful: false,
			ErrorMessage: "ID cannot be null",
			Post:         nil,
		})
		return
	}

	// get viewer from JWT
	viewerID := int64(-1)
	jwtStr := string(c.Cookie("JWT"))
	_, _, _, exp, id, err := auth_service.ParseUserJWT(ctx, jwtStr)
	if err == nil && exp > time.Now().Unix() {
		viewerID = id
	}
	// 若 JWT 不存在 / 解析失败 / 过期，则 viewerID 保持 -1，
	// 对应 service 中 IsLikedByUser / IsFavByUser 会默认 false，
	// 同时 view_count 不会自增。

	// 2) get post（内部会按规则自增 view_count）
	domainPostFull, err := post_service.GetPost(ctx, req.ID, viewerID)
	if err != nil {
		status := consts.StatusBadRequest
		if errors.Is(err, gorm.ErrRecordNotFound) {
			status = consts.StatusNotFound
		}
		c.JSON(status, post.GetPostByIDResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
			Post:         nil,
		})
		return
	}

	// 新版转换：domain.Post -> thrift.Post
	thriftPost := domain.DomainPostToThrift(*domainPostFull)

	c.JSON(consts.StatusOK, post.GetPostByIDResp{
		IsSuccessful: true,
		ErrorMessage: "",
		Post:         &thriftPost,
	})
}

// CreatePost .
// @router /post/create [POST]
func CreatePost(ctx context.Context, c *app.RequestContext) {
	var req post.CreatePostReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if req.GetTitle() == "" || req.GetContent() == "" {
		c.JSON(consts.StatusBadRequest, post.CreatePostResp{
			IsSuccessful: false,
			ErrorMessage: "Title or Content cannot be empty",
		})
		return
	}

	jwtStr := string(c.Cookie("JWT"))
	_, _, _, exp, id, err := auth_service.ParseUserJWT(ctx, jwtStr)
	if err != nil || id != req.GetUserID() {
		c.JSON(consts.StatusUnauthorized, post.CreatePostResp{
			IsSuccessful: false,
			ErrorMessage: err.Error() + ": Please Create Post using your own account",
		})
		return
	}
	if exp < time.Now().Unix() {
		c.JSON(consts.StatusUnauthorized, post.CreatePostResp{
			IsSuccessful: false,
			ErrorMessage: "Authentification info expired, please login again",
		})
		return
	}

	// ✅ 使用新版 CreatePost：带 media / tags / replyTo
	domainPost, err := post_service.CreatePost(
		ctx,
		req.GetUserID(),
		req.GetSchoolID(),
		req.GetTitle(),
		req.GetContent(),
		req.GetMediaType(), // string
		req.GetMediaUrls(), // []string
		req.Location,       // *string
		req.GetTags(),      // []string
		req.ReplyTo,        // *int64
	)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, post.CreatePostResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
		})
		return
	}

	// 新版转换：domain.Post -> thrift.Post
	thriftPost := domain.DomainPostToThrift(*domainPost)

	c.JSON(consts.StatusOK, post.CreatePostResp{
		IsSuccessful: true,
		ErrorMessage: "",
		Post:         &thriftPost,
	})
}

// if req.content or req.title is empty, corresponding cell in db will be updated to empty string!
// EditPost .
// @router /post/edit [POST]
func EditPost(ctx context.Context, c *app.RequestContext) {
	var req post.EditPostReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if req.GetTitle() == "" || req.GetContent() == "" {
		c.JSON(consts.StatusBadRequest, post.EditPostResp{
			IsSuccessful: false,
			ErrorMessage: "Title or Content cannot be empty",
		})
		return
	}

	// jwt
	jwtStr := string(c.Cookie("JWT"))
	_, _, _, exp, user_id, err := auth_service.ParseUserJWT(ctx, jwtStr)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, post.EditPostResp{
			IsSuccessful: false,
			ErrorMessage: "Error parsing JWT: " + err.Error(),
		})
		return
	}
	if exp < time.Now().Unix() {
		c.JSON(consts.StatusUnauthorized, post.EditPostResp{
			IsSuccessful: false,
			ErrorMessage: "Authentification info expired, please login again",
		})
		return
	}

	updatedPost, err := post_service.EditPost(
		ctx,
		user_id,
		req.GetID(),
		req.GetTitle(),
		req.GetContent(),
	)
	if err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, gorm.ErrRecordNotFound) {
			status = consts.StatusNotFound
		}
		c.JSON(status, post.EditPostResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
		})
		return
	}

	thriftPost := domain.DomainPostToThrift(*updatedPost)
	c.JSON(consts.StatusOK, post.EditPostResp{
		IsSuccessful: true,
		ErrorMessage: "",
		Post:         &thriftPost,
	})
}

// DeletePost .
// @router /post/delete [POST]
func DeletePost(ctx context.Context, c *app.RequestContext) {
	var req post.DeletePostReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	fmt.Println("Entered DeletePost", req.GetID())
	jwtStr := string(c.Cookie("JWT"))
	_, _, _, exp, userID, err := auth_service.ParseUserJWT(ctx, jwtStr)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, post.DeletePostResp{
			IsSuccessful: false,
			ErrorMessage: err.Error() + ": Please Delete Post using your own account",
		})
		return
	}
	if exp < time.Now().Unix() {
		c.JSON(consts.StatusUnauthorized, post.DeletePostResp{
			IsSuccessful: false,
			ErrorMessage: "Authentification info expired, please login again",
		})
		return
	}

	err = post_service.DeletePost(ctx, userID, req.GetID())
	if errors.Is(err, gorm.ErrRecordNotFound) {
		c.JSON(consts.StatusNotFound, post.DeletePostResp{
			IsSuccessful: false,
			ErrorMessage: "Post not found or no permission.",
		})
		return
	}
	if err != nil {
		c.JSON(consts.StatusInternalServerError, post.DeletePostResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, post.DeletePostResp{
		IsSuccessful: true,
		ErrorMessage: "",
	})
}

// GetSchoolRecentPosts .
// @router /post/school/recent [GET]
func GetSchoolRecentPosts(ctx context.Context, c *app.RequestContext) {
	var req post.GetSchoolRecentPostsReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if req.Limit == 0 {
		req.Limit = 10
	}

	// viewer（用于 is_liked_by_user / is_fav_by_user）
	viewerID := int64(-1)
	jwtStr := string(c.Cookie("JWT"))
	_, _, _, exp, id, err := auth_service.ParseUserJWT(ctx, jwtStr)
	if err == nil && exp > time.Now().Unix() {
		viewerID = id
	}

	posts, postIDToQuotedPosts, err := post_service.GetSchoolRecentPosts(
		ctx,
		req.SchoolID,
		viewerID,
		req.Before,
		int(req.Limit),
	)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, post.GetSchoolRecentPostsResp{
			IsSuccessful: false,
			ErrorMessage: "Failed to fetch posts: " + err.Error(),
			Posts:        nil,
		})
		return
	}

	resp := post.GetSchoolRecentPostsResp{
		IsSuccessful: true,
		ErrorMessage: "",
		QuotedPosts:  domain.DomainPostMapToThriftPointerMap(postIDToQuotedPosts),
		Posts:        domain.DomainPostListToThriftPointers(posts),
	}

	c.JSON(consts.StatusOK, resp)
}

// GetPersonalRecentPosts
// @router /post/personal [GET]
func GetPersonalRecentPosts(ctx context.Context, c *app.RequestContext) {
	var req post.GetPersonalRecentPostsReq

	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, post.GetPersonalRecentPostsResp{
			IsSuccessful: false,
			ErrorMessage: "Invalid request: " + err.Error(),
			Posts:        nil,
		})
		return
	}

	if req.Limit == 0 {
		req.Limit = 10 // default limit
	}

	// get viewer from JWT
	viewerID := int64(-1)
	jwtStr := string(c.Cookie("JWT"))
	_, _, _, exp, id, err := auth_service.ParseUserJWT(ctx, jwtStr)
	if err == nil && exp > time.Now().Unix() {
		viewerID = id
	}

	posts, postIDToQuotedPosts, err := post_service.GetPersonalRecentPosts(
		ctx,
		req.UserID,
		viewerID,
		req.Before,
		int(req.Limit),
	)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, post.GetPersonalRecentPostsResp{
			IsSuccessful: false,
			ErrorMessage: "Failed to fetch posts: " + err.Error(),
			Posts:        nil,
		})
		return
	}

	resp := post.GetPersonalRecentPostsResp{
		IsSuccessful: true,
		ErrorMessage: "",
		QuotedPosts:  domain.DomainPostMapToThriftPointerMap(postIDToQuotedPosts),
		Posts:        domain.DomainPostListToThriftPointers(posts),
	}

	c.JSON(consts.StatusOK, resp)
}

// LikePost .
// @router /post/like [POST]
func LikePost(ctx context.Context, c *app.RequestContext) {
	var req post.LikePostReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, newFailedUserFlagPostResq("Invalid request: "+err.Error()))
		return
	}

	// 从 JWT 拿 userID（失败时内部会返回 401 并结束）
	userID, ok := getViewerIDFromJWTOrWriteUnauthorized(ctx, c)
	if !ok {
		return
	}

	// service 层：只信 JWT 的 userID，忽略 req.UserId
	if err := post_service.LikePost(ctx, userID, req.PostID); err != nil {
		c.JSON(consts.StatusOK, newFailedUserFlagPostResq(err.Error()))
		return
	}

	c.JSON(consts.StatusOK, newSuccessUserFlagPostResq())
}

// UnlikePost .
// @router /post/unlike [POST]
func UnlikePost(ctx context.Context, c *app.RequestContext) {
	var req post.UnlikePostReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, newFailedUserFlagPostResq("Invalid request: "+err.Error()))
		return
	}

	userID, ok := getViewerIDFromJWTOrWriteUnauthorized(ctx, c)
	if !ok {
		return
	}

	if err := post_service.UnlikePost(ctx, userID, req.PostID); err != nil {
		c.JSON(consts.StatusOK, newFailedUserFlagPostResq(err.Error()))
		return
	}

	c.JSON(consts.StatusOK, newSuccessUserFlagPostResq())
}

// FavPost .
// @router /post/fav [POST]
func FavPost(ctx context.Context, c *app.RequestContext) {
	var req post.FavPostReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, newFailedUserFlagPostResq("Invalid request: "+err.Error()))
		return
	}

	userID, ok := getViewerIDFromJWTOrWriteUnauthorized(ctx, c)
	if !ok {
		return
	}

	if err := post_service.FavoritePost(ctx, userID, req.PostID); err != nil {
		c.JSON(consts.StatusOK, newFailedUserFlagPostResq(err.Error()))
		return
	}

	c.JSON(consts.StatusOK, newSuccessUserFlagPostResq())
}

// UnfavPost .
// @router /post/unfav [POST]
func UnfavPost(ctx context.Context, c *app.RequestContext) {
	var req post.UnfavPostReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, newFailedUserFlagPostResq("Invalid request: "+err.Error()))
		return
	}

	userID, ok := getViewerIDFromJWTOrWriteUnauthorized(ctx, c)
	if !ok {
		return
	}

	if err := post_service.UnfavoritePost(ctx, userID, req.PostID); err != nil {
		c.JSON(consts.StatusOK, newFailedUserFlagPostResq(err.Error()))
		return
	}

	c.JSON(consts.StatusOK, newSuccessUserFlagPostResq())
}

// helper: build a failed UserFlagPostResq
func newFailedUserFlagPostResq(msg string) post.UserFlagPostResq {
	return post.UserFlagPostResq{
		IsSuccessful: false,
		ErrorMessage: msg,
	}
}

// helper: build a success UserFlagPostResq
func newSuccessUserFlagPostResq() post.UserFlagPostResq {
	return post.UserFlagPostResq{
		IsSuccessful: true,
		ErrorMessage: "",
	}
}

// helper: get viewerID from JWT cookie.
//
// 返回：
//   - viewerID: 合法用户 ID
//   - ok:       是否成功；如果 false，函数内部已经写了 Unauthorized 响应
func getViewerIDFromJWTOrWriteUnauthorized(
	ctx context.Context,
	c *app.RequestContext,
) (int64, bool) {
	jwtStr := string(c.Cookie("JWT"))

	_, _, _, exp, uid, errJWT := auth_service.ParseUserJWT(ctx, jwtStr)
	if errJWT != nil || exp <= time.Now().Unix() {
		// 解析失败或者过期
		c.JSON(consts.StatusUnauthorized, newFailedUserFlagPostResq("Unauthorized"))
		return -1, false
	}

	return uid, true
}

// UploadPostMedia .
// @router /post/media/upload [POST]
func UploadPostMedia(ctx context.Context, c *app.RequestContext) {
	// 1. JWT 鉴权，拿 userID
	jwtStr := string(c.Cookie("JWT"))

	_, _, _, exp, userID, err := auth_service.ParseUserJWT(ctx, jwtStr)
	if err != nil {
		fmt.Println("Error when testing:", err.Error())
	}

	if err != nil || exp < time.Now().Unix() {
		c.JSON(consts.StatusUnauthorized, post.UploadPostMediaResp{
			IsSuccessful: false,
			ErrorMessage: "unauthorized, please login again",
		})
		return
	}

	// 2. 解析 multipart/form-data
	form, err := c.MultipartForm()
	if err != nil {
		c.JSON(consts.StatusBadRequest, post.UploadPostMediaResp{
			IsSuccessful: false,
			ErrorMessage: "invalid multipart form: " + err.Error(),
		})
		return
	}

	// 前端约定字段名，比如 "images"
	files := form.File["images"]
	if len(files) == 0 {
		c.JSON(consts.StatusBadRequest, post.UploadPostMediaResp{
			IsSuccessful: false,
			ErrorMessage: "no files uploaded",
		})
		return
	}

	// 3. 调用你刚写的 service，上传到 S3
	urls, err := picture_upload_service.UploadPostImages(ctx, userID, files)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, post.UploadPostMediaResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
		})
		return
	}

	// 4. 返回 thrift 定义的 resp
	c.JSON(consts.StatusOK, post.UploadPostMediaResp{
		IsSuccessful: true,
		ErrorMessage: "",

		Urls: urls,
	})
}
