// Code generated by hertz generator.

package base

import (
	"context"

	school "zetian-personal-website-hertz/biz/model/school"
	"zetian-personal-website-hertz/biz/repository/school_repo"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetAllSchools .
// @router /school/all [GET]
func GetAllSchools(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school.GetAllSchoolsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	schools, err := school_repo.GetAllSchoolsInCache()
	if err != nil {
		c.JSON(consts.StatusInternalServerError, school.GetAllSchoolsResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
		})
		return
	}

	thriftSchools := make([]*school.School, 0, len(schools))
	for _, s := range schools {
		thriftSchools = append(thriftSchools, &school.School{
			ID:          s.ID,
			Name:        s.Name,
			ShortName:   s.ShortName,
			Aliases:     s.Aliases,
			Description: s.Description,
		})
	}

	c.JSON(consts.StatusOK, school.GetAllSchoolsResp{
		IsSuccessful: true,
		ErrorMessage: "",
		Schools:      thriftSchools,
	})
}
