// Code generated by hertz generator.
package base

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"zetian-personal-website-hertz/biz/config"
	user "zetian-personal-website-hertz/biz/model/user"
	authService "zetian-personal-website-hertz/biz/service/auth_service"
	userService "zetian-personal-website-hertz/biz/service/user_service"
)

/*
All JWTs that are stored in cookie
"JWT": user's basic information

"VeriEmailJWT": means verification email JWT, used to verify user's email for sign up, reset password, etc.
*/

// Login .
// @router /login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var req user.LoginReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, fmt.Sprintf("Invalid request: %v", err))
		return
	}
	fmt.Println(req.GetEmail(), "password:", req.GetPassword())
	// 验证用户名密码
	domainUser, err := userService.Login(ctx, req.GetEmail(), req.GetPassword())
	if err != nil {
		c.JSON(consts.StatusUnauthorized, user.LoginResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
		})
		return
	}

	// 生成 JWT 并设置 Cookie
	token, err := authService.GenerateUserJWT(ctx, -1, int64(domainUser.ID), domainUser.Username, domainUser.Email, -1)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, user.LoginResp{
			IsSuccessful: false,
			ErrorMessage: "JWT generation failed",
		})
		return
	}

	c.SetCookie("JWT",
		token,
		int(3600*24*7),
		"/",
		config.GetSpecificConfig().Domain,
		protocol.CookieSameSiteLaxMode,
		config.GetSpecificConfig().CookieSecure,
		true) // HttpOnly Cookie

	c.JSON(consts.StatusOK, user.LoginResp{
		IsSuccessful: true,
		UserName:     domainUser.Username,
		Email:        domainUser.Email,
	})
}

// SignUp .
// @router /signup [POST]
func SignUp(ctx context.Context, c *app.RequestContext) {
	var req user.SignUpReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, fmt.Sprintf("Invalid request: %v", err))
		return
	}
	veriEmailJWT := string(c.Cookie("VeriEmailJWT"))

	//verify whether the user has the veriEmail to signUp
	email, veriEmailExp, purpose, err := authService.ParseVeriEmailJWT(ctx, veriEmailJWT)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, user.SignUpResp{
			IsSuccessful: false,
			ErrorMessage: err.Error() + ", Please get verification code first",
		})
		return
	}
	if email != req.GetEmail() || strings.ToLower(purpose) != "signup" {
		c.JSON(consts.StatusUnauthorized, user.SignUpResp{
			IsSuccessful: false,
			ErrorMessage: "Action Unauthorized",
		})
		clearVeriEmailCookie(c)
		return
	}
	if veriEmailExp < time.Now().Unix() {
		c.JSON(consts.StatusUnauthorized, user.SignUpResp{
			IsSuccessful: false,
			ErrorMessage: "The verification code has expired, get a new code first",
		})
		return
	}

	err = userService.SignUp(ctx, req.GetUsername(), req.GetPassword(), req.GetEmail())

	if err != nil {
		c.JSON(consts.StatusBadRequest, user.SignUpResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, user.SignUpResp{
		IsSuccessful: true,
		UserName:     req.GetUsername(),
		Email:        req.GetEmail(),
	})
	//clear the veriEmailJWT, disabling user's ability to modify email
	clearVeriEmailCookie(c)
}

func clearVeriEmailCookie(c *app.RequestContext) {
	c.SetCookie("VeriEmailJWT", "", -1, "/", config.GetSpecificConfig().Domain,
		protocol.CookieSameSiteLaxMode, config.GetSpecificConfig().CookieSecure, true)
}

func clearAuthCookie(c *app.RequestContext) {
	c.SetCookie("JWT", "", -1, "/", config.GetSpecificConfig().Domain,
		protocol.CookieSameSiteLaxMode, config.GetSpecificConfig().CookieSecure, true)
}

// GetUser .
// @router /user/get [GET]
func GetUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if req.ID < 0 {
		c.JSON(consts.StatusBadRequest, user.GetUserResp{
			IsSuccessful: false,
			ErrorMessage: "ID must be positive",
			UserName:     "",
			ID:           -1,
		})
		return
	}

	if req.ID != 0 && req.Name != "" {
		c.JSON(consts.StatusBadRequest, user.GetUserResp{
			IsSuccessful: false,
			ErrorMessage: "Only one of ID and UserName should be provided",
			UserName:     "",
			ID:           -1,
		})
		return
	}

	if req.ID != 0 {
		domainUser, err := userService.GetUserByID(ctx, req.ID)
		if err != nil {
			c.JSON(consts.StatusInternalServerError, user.GetUserResp{
				IsSuccessful: false,
				ErrorMessage: err.Error(),
				UserName:     "",
				ID:           -1,
			})
			return
		}
		c.JSON(consts.StatusOK, user.GetUserResp{
			IsSuccessful: true,
			ErrorMessage: "",
			UserName:     domainUser.Username,
			ID:           int64(domainUser.ID),
		})
		return
	}

	domainUser, err := userService.GetUserByUsername(ctx, req.Name)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, user.GetUserResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
			UserName:     "",
			ID:           -1,
		})
		return
	}
	c.JSON(consts.StatusOK, user.GetUserResp{
		IsSuccessful: true,
		ErrorMessage: "",
		UserName:     domainUser.Username,
		ID:           int64(domainUser.ID),
	})

}

// Logout .
// @router logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LogoutReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	clearAuthCookie(c)
	c.JSON(consts.StatusOK, user.LogoutResp{
		IsSuccessful: true,
		ErrorMessage: "",
	})
}

// ResetPassword .
// @router /user/reset-password [POST]
func ResetPassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.ResetPasswordReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	veriEmailJWT := string(c.Cookie("VeriEmailJWT"))

	//verify whether the user has the veriEmail to signUp
	email, veriEmailExp, purpose, err := authService.ParseVeriEmailJWT(ctx, veriEmailJWT)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, user.ResetPasswordResp{
			IsSuccessful: false,
			ErrorMessage: err.Error() + ", Please get verification code first",
		})
		return
	}
	if email != req.GetEmail() || strings.ToLower(purpose) != "resetpassword" {
		//it means the user is copy pasting JWT from others or from other actions
		c.JSON(consts.StatusUnauthorized, user.ResetPasswordResp{
			IsSuccessful: false,
			ErrorMessage: "Action Unauthorized",
		})
		clearVeriEmailCookie(c)
		return
	}
	if veriEmailExp < time.Now().Unix() {
		c.JSON(consts.StatusUnauthorized, user.ResetPasswordResp{
			IsSuccessful: false,
			ErrorMessage: "The verification code has expired, get a new code first",
		})
		return
	}

	err = userService.ResetPassword(ctx, req.GetEmail(), req.GetNewPassword())
	if err != nil {
		c.JSON(consts.StatusBadRequest, user.ResetPasswordResp{
			IsSuccessful: false,
			ErrorMessage: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, user.ResetPasswordResp{
		IsSuccessful: true,
		ErrorMessage: "",
	})
	//clear the veriEmailJWT, disabling user's ability to modify email
	clearVeriEmailCookie(c)


}

