// Code generated by hertz generator.

package base

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	verification "zetian-personal-website-hertz/biz/model/verification"
)

// SendVeriCodeToEmail .
// @router /verification/email/send-code [POST]
func SendVeriCodeToEmail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req verification.SendVeriCodeToEmailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(verification.SendVeriCodeToEmailResp)


	
	c.JSON(consts.StatusOK, resp)
}

// VerifyEmailCode .
// @router /verification/email/verify-code [POST]
func VerifyEmailCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req verification.VerifyEmailCodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(verification.VerifyEmailCodeResp)

	c.JSON(consts.StatusOK, resp)
}
