// Code generated by hertz generator.

package base

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettobinaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verificationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _emailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendvericodetoemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verifyemailcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _meMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _editpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpostbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getallpersonalpostsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _schoolMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getschoolrecentpostsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpersonalrecentpostsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unfavpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unlikepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _school0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getallschoolsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mediaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadpostmediaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateavatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getallcategoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unfollowuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfolloweesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfollowersMw() []app.HandlerFunc {
	// your code...
	return nil
}
