// Code generated by hertz generator.

package base

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettobinaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verificationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _emailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendvericodetoemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verifyemailcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}
