// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	main "zetian-personal-website-hertz/biz/router/main"
	numberOperation "zetian-personal-website-hertz/biz/router/numberOperation"
	user "zetian-personal-website-hertz/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	main.Register(r)

	user.Register(r)

	numberOperation.Register(r)
}
